version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:18.7.0-ce.0
    container_name: gitlab_ce
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://你的地址:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '8443:443'
      - '2424:22'
    volumes:
      - '/home/ubuntu/gitlab/config:/etc/gitlab'
      - '/home/ubuntu/gitlab/logs:/var/log/gitlab'
      - '/home/ubuntu/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'

