concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "ollama"
  url = "http://192.168.40.249:8929"
  id = 8
  token = "glrt-FXCY56HIRzNAe5m_RcEItW86MQpwOjUKdDozCnU6MQ8.01.17017rudt"
  token_obtained_at = 2026-01-03T06:23:06Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false      #DinD模式必须金庸
    image = "docker:24.0.7" #指定镜像版本
    privileged = true       #必须开启
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/certs/client","/cache"]  #最好提前创建
    shm_size = 1036870912  
    network_mtu = 1450
    cpus = "4"
    memory = "8g"